wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1719370738
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.8.16
      5: 0.17.1
      6: 4.41.2
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
